### ISSUE TITLE
How many hits can a server handle?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#10]
How many hits can a Heroku ("free tier") server handle?

**Comment by nelsonic** [comment]
I feel a Performance test project coming along sooon... :wink:

**Comment by besarthoxhaj** [comment]
@nelsonic that would be amazing!:)

**Comment by nelsonic** [comment]
Tested on my _ancient_ MacBook Air:
![image](https://user-images.githubusercontent.com/194400/30137688-68c3e24a-935c-11e7-8c59-71d69b8444d3.png)

On Linode with NGINX Proxying Node:
![image](https://user-images.githubusercontent.com/194400/30137744-ae605c7a-935c-11e7-85da-3071131f4e42.png)

Getting a _lot_ of "failed requests" ... 

Turned down concurrency level to **10** and got:
![image](https://user-images.githubusercontent.com/194400/30137775-de107798-935c-11e7-8d25-54d486e868da.png)

I think this requires more investigation.
I intend to do a head-to-head comparison with Elixir shortly. 🆚 😮

**Comment by nelsonic** [comment]
Need to _investigate_ how to benchmark the Elixir version ... currently getting:
```
Benchmarking localhost (be patient)

Test aborted after 10 failures

apr_socket_connect(): Operation already in progress (37)
Total of 6 requests completed
```
![image](https://user-images.githubusercontent.com/194400/30206705-cf336428-9484-11e7-94d2-f427012dc9fa.png)

**Comment by nelsonic** [comment]
Need to _investigate_ how to benchmark the Elixir version ... currently getting:
```
Benchmarking localhost (be patient)

Test aborted after 10 failures

apr_socket_connect(): Operation already in progress (37)
Total of 6 requests completed
```
![image](https://user-images.githubusercontent.com/194400/30206705-cf336428-9484-11e7-94d2-f427012dc9fa.png)

**Comment by nelsonic** [comment]
Moved to Fly.io with Postgres on an "Elastic" attached storage. 🚀 
Closing. ✅
