### ISSUE TITLE
cookie-less hits counter

### ISSUE THREAD

**Issue by stangri** [dwyl/hits#112]
Is it possible to get a cookie-less hits counter? I realize that the views may be inflated, but having no cookies placed is more important.

**Comment by nelsonic** [comment]
@stangri what makes you think that Hits is using Cookies? 💭

**Comment by stangri** [comment]
I have a cookie from hits.dwyl.com in my browser.

**Comment by nelsonic** [comment]
Ah ... You're right! 🤔 
![image](https://user-images.githubusercontent.com/194400/94816639-feb2d080-03f3-11eb-8139-ae3f7517c318.png)

that's a Cloudflare Cookie https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies

We _could_ consider removing CloudFlare for this subdomain ... 💭

**Comment by stangri** [comment]
Follow-up question exceeding the scope of the original issue: what kind of data is stored by hits.dwyl.com on counted hits? Do you store IP addresses in the logs?
