### ISSUE TITLE
2 times hits when clicking the overview button

### ISSUE THREAD

**Issue by navierr** [dwyl/hits#116]
Hi!

Here is what I recorded :
![녹화_2021_04_06_20_45_19_633](https://user-images.githubusercontent.com/69755061/113707503-f5941a80-971a-11eb-83c2-4a228e00e69d.gif)

I noticed this while looking at someone's GitHub profile. 
It doesn't seem to be working properly.

**Comment by nelsonic** [comment]
Hi @navierr, 👋  
We do not have that style of button so this is someone who has forked the project and is running their own hit counter. 👍 
what would **`73 / 18952`** even _mean_ ...? 🤷‍♂️

**Comment by navierr** [comment]
Oh, I'm really sorry. 😥
I didn't look carefully, and I misunderstood that the badge was from this project. 🤦‍♂️
I apologize for opening an issue for my misunderstanding.

**Comment by nelsonic** [comment]
@navierr no need to apologise. You had no way of guessing. 👍 
But for future reference, it's quite easy to check. 🔍 
Just view the page and see where the source of the image is: https://github.com/utilforever

<img width="683" alt="Screenshot 2021-04-07 at 12 27 09" src="https://user-images.githubusercontent.com/194400/113859711-20bf4e00-979d-11eb-9ce2-b1d2e2b5ed89.png">

Or view it directly in the code on GitHub:  https://github.com/utilForever/utilForever/edit/master/README.md

<img width="683" alt="Screenshot 2021-04-07 at 12 27 09" src="https://user-images.githubusercontent.com/194400/113859418-c6be8880-979c-11eb-9007-b3fd7bdc3b3f.png">

One of the beauties of Open Source is that _anyone_ can fork the project and run their own instance. ❤️ ✅
