### ISSUE TITLE
Continuous Deployment with Fly and GitHub Actions

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#132]
We recently deployed our "Hits" app to fly.io: https://github.com/dwyl/hits/pull/128 but we did it _manually_ ...
What we want is an _automated_ way of deploying (_continuously_) when a PR is merged.

# Todo

+ [x] Replace Travis-CI with GitHub Actions for the Hits project 
  see: https://github.com/dwyl/learn-travis/issues/67
+ [x]  Read these instructions and apply them to the Hits project: 
https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

**Comment by nelsonic** [comment]
PR: #133 :shipit:
Assigned to @SimonLab for review. 🙏 
The deploy script already worked to deploy the latest version of the app see: https://github.com/dwyl/hits/pull/131#issuecomment-980545902 🚀

**Comment by SimonLab** [comment]
Thanks for adding the deploy section for fly.io @nelsonic .
PR merged :+1

**Comment by nelsonic** [comment]
@SimonLab how can we **`test`** that the auto-deploy is working? 🤷‍♂️ 
Should we make a micro-change to the homepage and _confirm_ it gets deployed when the PR is merged? 💭

**Comment by nelsonic** [comment]
Micro-PR: https://github.com/dwyl/hits/pull/136 🤞

**Comment by nelsonic** [comment]
Working. See: https://github.com/dwyl/hits/pull/136#issuecomment-981054138
