### ISSUE TITLE
Review hits changeset and insert

### ISSUE THREAD

**Issue by SimonLab** [dwyl/hits#134]
While searching why the hits count doesn't increase (see: https://github.com/dwyl/hits/pull/131#issuecomment-980545902)
I noticed the insert function seems incorrect.
The  `attrs` values should be passed as the second argument to the changeset however the pipe in the insert places it as first argument:

https://github.com/dwyl/hits/blob/e046a9158916b91b381ec88d1c08ab5cad9d7403/lib/hits/hit.ex#L14-L26

I think this should instead be:
```elixir
  def insert(attrs) do
    changeset(%{}, attrs) |> Hits.Repo.insert()
    # see: github.com/dwyl/hits/issues/71
    attrs.repo_id
    |> get_aggregate_query()
    |> Repo.aggregate(:count, :id)
  end
```

The changeset doesn't cast or required any values so I'm not sure if it returns an empty `Hit` or if it returns all the values, I'll need to test it manually to see what is saved in the database.

@nelsonic I'm not sure if there is an easy way to look at the database with fly.io?

**Comment by nelsonic** [comment]
Yeah, the weird thing is that this works on localhost. Putting my distributed systems / high availability hat on, I think this request is hitting the “read replica” … Fly.io forces us to have ***two*** instances of PostgreSQL. I think this request might read from the Read instance and thus does not increment. 💭

**Comment by SimonLab** [comment]
I've checked also on localhost and everything seems to work properly.
The insert functions don't really use the changeset at the moment and insert the new `Hit` passed as attributes.
I don't know how fly.io works with Postgres yet but I will read about it and try to understand what causes the issue.

**Comment by nelsonic** [comment]
@SimonLab are you adding anything else to the PR #137 ? 💭 
And do we need to do a `mix ecto.migrate` for this to work or can we just ship it? :shipit:

**Comment by SimonLab** [comment]
I still want to have a bit more look at the schemas, I think it's possible to create a "hit" entry without having to create all the other steps manually first:

https://github.com/dwyl/hits/blob/f389abdf413ecae50c44676bdc630e825a14ffa2/lib/hits_web/controllers/hit_controller.ex#L31-L63

**Comment by nelsonic** [comment]
@SimonLab we kinda *want* this data to be stored though … we’re you thinking we would store the data in an ETS Cache and simply increment the counter and return that. And then once the response is sent the cache would be cleared in the background? 💭

**Comment by SimonLab** [comment]
I still want to save all the data in Postgres, I want to try to use one hit changeset to manage all the `inserts`. I think Ecto can decide if an associated items should be created or just retrieved from the database, instead writing these steps manually in the code.
I need to have a better look at the Ecto documentation and doing some tests with all the associations.

**Comment by nelsonic** [comment]
@SimonLab been thinking that maybe we should restore the "old" behaviour for hits i.e. increment the counter/badge on each page view. But then add the functionality to show only unique views for people who want it via URL query param e.g: `&show=unique`

**Comment by SimonLab** [comment]
@nelsonic I've created this [PR](https://github.com/dwyl/hits/pull/138) which add the `show=unique` query parameter, let me know if this work :+1:

**Comment by nelsonic** [comment]
@SimonLab your change appears to have deployed successfully to Fly.io: https://hits.dwyl.com/ 👍🏻

**Comment by SimonLab** [comment]
A quick overview of associations in Ecto:

[![image](https://user-images.githubusercontent.com/6057298/150959585-a05d1b14-8ec8-480f-a5a1-79a6863c333e.png)](https://www.youtube.com/watch?v=TluqRHbsDDk&ab_channel=AlchemistCamp)

**Comment by SimonLab** [comment]
I've added two new migrations with https://github.com/dwyl/hits/pull/137/commits/462ff16a8e57ea811dbe5bbdb67ad66bdbf66560 which defined `unique_index` on the `useragents` and `users` table. This allow us to check at a database level that we don't have any duplicates created (name + ip must be different for entries in `useragents` and name are all different on `users`).
Now we can simplify the `insert` functions:

https://github.com/dwyl/hits/blob/eddc463393147d959cdbbf6cbd2b1acc51129c1f/lib/hits/user.ex#L30-L39

https://github.com/dwyl/hits/blob/eddc463393147d959cdbbf6cbd2b1acc51129c1f/lib/hits/useragent.ex#L30-L39

and use instead the [upsert feature](https://hexdocs.pm/ecto/constraints-and-upserts.html#upserts) by using the [`on_conflict` option](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2-options)

I'm also looking at adding a `unique_index` on the repository table, we want the name and the user_id to be unique in this case.

**Comment by nelsonic** [comment]
@SimonLab saw your additions on the branch/PR. Look good. 👍 
Only thing I would say is: try and document the changes in the `README.md` so that _other_ people understand them. 💭

**Comment by SimonLab** [comment]
done with #137
