### ISSUE TITLE
Use `String.end_with` to check .svg request

### ISSUE THREAD

**Issue by SimonLab** [dwyl/hits#135]
At the moment we check the repository contains ".svg" to increase the count number:
https://github.com/dwyl/hits/blob/b58d74e2c0b75392de2ca8b1228e6ee17bace637/lib/hits_web/controllers/hit_controller.ex#L8

However it is possible to create repository name that contains `.svg` in the middle of the string:

![image](https://user-images.githubusercontent.com/6057298/143719973-f74c65c0-173e-4d3b-acbb-6e19bc870c2b.png)

We can improve this line of code by using a regex or [String.end_with](https://hexdocs.pm/elixir/1.12/String.html#ends_with?/2)

```elixir
if String.end_with?(repository, ".svg")  do
```

**Comment by nelsonic** [comment]
@SimonLab good idea. 💡
