### ISSUE TITLE
Mix.Config is deprecated

### ISSUE THREAD

**Issue by SimonLab** [dwyl/hits#139]
Compiling the project with Elixir 1.13.2 displays the following warning:
![image](https://user-images.githubusercontent.com/6057298/150773322-51d111ba-29b5-4a39-813c-2182c174fcd8.png)

Indeed:
![image](https://user-images.githubusercontent.com/6057298/150773541-5b1ce2f5-aa05-4e62-9cb6-db416eddf1ac.png)
 See https://hexdocs.pm/mix/1.12/Mix.Config.html

- [x] Replace Mix.config module with the Config module

**Comment by SimonLab** [comment]
This issue should be fixed with the following commit:
https://github.com/dwyl/hits/pull/137/commits/7a9065451c0967b8a4658725691628e28569b62c

updating `use Mix.Config` to `import Config` seems to work.

**Comment by nelsonic** [comment]
Included in PR #137 (Merged) ✅
