### ISSUE TITLE
Auto Deploy to Fly.io ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#140]
@SimonLab your PR #137 appears to not have deployed, 
see: https://github.com/dwyl/hits/runs/5100974307?check_suite_focus=true#step:4:448

Let me know if you need help with debugging this. Thanks!

**Comment by SimonLab** [comment]
Thanks for creating the issue.
I suppose this is where the error occurs:
![image](https://user-images.githubusercontent.com/6057298/153010363-6a3295a1-ed17-480e-a66d-7c996b2b8843.png)

So I suppose the new migration which creates the `unique_index` on the `useragents` table failed because there are already some duplicates in the table.
I'll need to connect to the Postgres database and query the table to search for these duplicates and remove them manually if there aren't linked to any `hits`

**Comment by SimonLab** [comment]
I've finally managed after a few tries to connect to postgres using `flyctl`:

1. login to fly.io with `flyctl auth login` https://fly.io/docs/flyctl/auth/
2. login to postgres with `flyctl postgres connect -a hits-db` I blocked on this step as first I didn't specify the postgres application to connect to. Then I had to update the image:
![image](https://user-images.githubusercontent.com/6057298/153937822-eb68e542-0a81-4e8d-be38-6dcb614bdb87.png)

So if this happen run
- `flyctl image show -a hits-db` again specify the hits-db application
The following messages is displayed:
```sh
Update available! (flyio/postgres:13.4 v0.0.7 -> flyio/postgres:13.5 v0.0.14)
Run `flyctl image update` to migrate to the latest image version.
```
- so run `flyctl image update -a hits-db` this will take a couple of minutes
- then try again `flyctl postgres connect -a hits-db` and I'm not able to inspect the entries on the databae

**Comment by SimonLab** [comment]
queries to find duplicates:
```sql
select id, name, ip from useragents ou where (select count(name) from useragents inr where inr.name = ou.name and inr.ip = ou.ip) > 1;
```
![image](https://user-images.githubusercontent.com/6057298/153949507-fa7c8a58-62cd-47c0-9ce7-72543ab0cf87.png)

``` sql
select id, name from users ou where (select count(name) from users inr where inr.name = ou.name) > 1;
```
![image](https://user-images.githubusercontent.com/6057298/153949696-e47fee38-c801-4b8f-91c2-518aa6d9165c.png)

```sql
select id, name, user_id from repositories ou where (select count(name) from repositories inr where inr.name = ou.name and inr.user_id = ou.user_id) > 1;
```
No duplicates found for repositories


We don't have a lot of duplicates, so I think we can remove them manually from the database and try to rerun the deployment where the new ecto migrations will add unique index

**Comment by nelsonic** [comment]
@SimonLab sounds good. 👍🏻

**Comment by SimonLab** [comment]
I'm not sure how it was resolved. The first attempt ran the migration but the deployement failed. I've rerun the deployement this time no migrations were needed to run as they were done on the first attempt and the deployment succeeded!
@nelsonic I think the latest version (main branch) is now running on fly.io

**Comment by SimonLab** [comment]
The application is now deployed on Fly.io

**Comment by nelsonic** [comment]
Thanks for confirming @SimonLab 👍
