### ISSUE TITLE
Remove "Updates will appear here when WebSockets are working ..." Text

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#149]
Simon fixed the WebSockets issue #129 so the updates are showing on https://hits.dwyl.com

![Screen Shot 2022-03-08 at 10 23 01](https://user-images.githubusercontent.com/194400/157220356-4330992e-4c46-4bcb-bbcd-dce5bcb4c5a5.png)

But the text is still there: "Updates will appear here when WebSockets are working ..." 

# Todo

+ [x] Replace the text with the updates when WebSockets are working.

**Comment by SimonLab** [comment]
This should be fixed with #151
I've added an id to the div which display the default text and when new socket messages arrive I check if the div exist and remove it.

**Comment by nelsonic** [comment]
Thanks for removing this @SimonLab
