### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#157]
https://hits.dwyl.com/test/test.svg
![image](https://user-images.githubusercontent.com/194400/163268530-12af9b5a-c93c-4ce1-941b-89702304b8ac.png)

Lame. 🙄

**Comment by nelsonic** [comment]
The homepage still renders: https://hits.dwyl.com/
![image](https://user-images.githubusercontent.com/194400/163268665-3e8e1912-58ef-472a-b0cc-ddca43839129.png)

But the badges don't. 🤷‍♂️

**Comment by SimonLab** [comment]
The deploy failed because of Postgres being unavailable:
> Error: :54.363 [error] Postgrex.Protocol (#PID<0.136.0>) failed to connect: ** (DBConnection.ConnectionError) tcp recv: closed

I had a similar error yesterday on another application using Postgres with Fly.io.
I've restarted the application database with fly. It took a bit of time to be fixed but it might be worth to try.

`flyctl restart hits-db`

We can also check the status of the database with `flyctl status -a hits-db`

see https://fly.io/docs/flyctl/restart/

**Comment by SimonLab** [comment]
I think the error is still there (or appears again)
@nelsonic do you know if the hits application is running under the `dwyl` organisation on Fly.io? If so, if you invite me to the application I can have a look at the logs and try to see what is the issue.

**Comment by nelsonic** [comment]
The hits app is currently a `personal` ...  let's fix that!  https://fly.io/docs/flyctl/apps-move/
Org: https://fly.io/organizations/hits

```sh
flyctl apps move hits-db --org hits
flyctl apps move hits --org hits
```

Get the following warning:

```sh
Moving an app between organizations requires a complete shutdown and restart. This will result in some app downtime.
If the app relies on other services within the current organization, it may not come back up in a healthy manner.
Please confirm whether you wish to restart this app now.
? Move app hits-db? (y/N)
```

I invited you to the `hits` org so you should have admin access. 

The transfer restarted both the app and the db and hit badges appear to be working again:

[![HitCount](http://hits.dwyl.com/dwyl/gogs-server.svg)](http://hits.dwyl.com/dwyl/gogs-server)

**Comment by bartandrews** [comment]
I am also experiencing this problem, suddenly happened as of yesterday/today. It was working fine for 3 months, not sure why I suddenly get "internal server error" here https://hits.dwyl.com/HofstadterTools/HofstadterToolsgithubio  Any help would be much appreciated!

**Comment by nelsonic** [comment]
Lame ... 😢 ⏳

**Comment by LuchoTurtle** [comment]
@bartandrews it should be working at the time of writing (see #266 for more context). If anything happens again, ping us :D
