### ISSUE TITLE
Add customization parameters to the badges we can generate with your site?

### ISSUE THREAD

**Issue by TF2CutContentWiki** [dwyl/hits#190]
I don't seem to be able to modify the color of the badge using some similar parameters that the shields.io badges have, such as `label`, `color` and `labelColor`. Any chance of adding those two parameters in?

What I specifically am trying to do, is this:

`https://hits.dwyl.com/TF2CutContentWiki/TF2CutContentWiki.svg?style=flat-square&color=%23545D6F&labelColor=%23434C5E&label=Views`

**Comment by nelsonic** [comment]
Hi @TF2CutContentWiki 👋 
yes, we totally want to add customisation. 👌 
We were thinking of doing it via Shields.io Endpoint: https://github.com/dwyl/hits/issues/168 💭 

As always Pull Requests (ideally with docs & tests) always welcome. 🙏 

You have write access: https://github.com/dwyl/hits/invitations
<img width="857" alt="image" src="https://user-images.githubusercontent.com/194400/193206071-d5c3112e-4655-4531-a605-9c94c19a6103.png">


CC: @LuchoTurtle want to pair on this as an intro task next week? 📆

**Comment by TF2CutContentWiki** [comment]
I see your invite to collab, but I really don't know how the shields.io stuff works 😅

**Comment by TF2CutContentWiki** [comment]
Whoops, didn't realize this was covered by #168
