### ISSUE TITLE
`520` Error ... 😢 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#214]
https://hits.dwyl.com/
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/194400/218067313-1839c208-1763-4dae-93c3-066f770e4e35.png">

Investigating. 🔍

**Comment by nelsonic** [comment]
Metrics look fine: https://fly.io/apps/hits/metrics?range=21600
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/194400/218068303-9fd24ca0-1850-4bc7-a2d2-d8302c023bec.png">

https://fly-metrics.net/d/fly-app/fly-app?orgId=26413&var-app=hits
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/194400/218068026-9cf61ab5-4836-426d-aac8-5334dfc03e08.png">

Doubled the memory to **`512Mb`** ... let's see if that does it. ⏳ 

Deploying new version:

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/194400/218068607-dbd28ea7-143f-479e-8df0-38b9d5d9e2d8.png">

Meanwhile all those requests are hitting the server ... 🤦‍♂️ 

DB seems to be running fine:
https://fly-metrics.net/d/fly-app/fly-app?orgId=26413&var-app=hits-db
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/194400/218067692-95d90df9-fc7a-4968-bfea-0be26fcae086.png">

**Comment by nelsonic** [comment]
Unresponsive ...
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/194400/218068863-36283d85-ac3c-46d5-aa34-cf8af3c58868.png">

Not great. Closing the page and will return to it after refilling my water bottle. 🚰 ⏳

**Comment by SimonLab** [comment]
Tested on my side and the page seems to be loading correctly:
![image](https://user-images.githubusercontent.com/6057298/218071645-4b062172-fbfa-4fae-b472-6dc15ecac38f.png)

**Comment by nelsonic** [comment]
Working again for me too: 
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/194400/218071967-b27b9ca6-a879-4f08-b1d1-64b4d6bf01b6.png">

Thanks for checking @SimonLab
