### ISSUE TITLE
add hits as a dwyl service available to everyone at hits.dwyl.io ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#22]
@iteles I thought this might be useful to us _specifically_ to track the visits on our projects on github
and I will be enhancing it as the built-in analytics for https://github.com/nelsonic/adoro ...
Do you think its worth having it as a service for others exposed on hits.dwyl.io ?

**Comment by iteles** [comment]
It's _extremely_ useful, especially as it gives the people using it access to all the data. :+1: 
Exposing it as a service with a 'dashboard' at hits.dwyl.io? 
I'd make that a temporary location for it, but long term it might deserve its own home.

**Comment by nelsonic** [comment]
I want to avoid ~~buying~~ ***RENTING*** anymore domains if I can help it.

**Comment by iteles** [comment]
Totally agree. I'm thinking a year down the line we need to reevaluate and see if it fits with everything else we're doing under the _dwyl_ :closed_umbrella:  (because the open umbrella has rain and that's just _saaaaaaaaad panda_ :umbrella: :sob: :panda_face: )

**Comment by nelsonic** [comment]
You have the power... :battery:

**Comment by nelsonic** [comment]
http://hits.dwyl.io
![image](https://user-images.githubusercontent.com/194400/29789947-b8e9bc1a-8c2f-11e7-8746-03be1200a257.png)
