### ISSUE TITLE
Fetching JSON or any other API hits data returns 500 Internal Server Error 

### ISSUE THREAD

**Issue by D00Movenok** [dwyl/hits#266]
Hi there! I've been using your awesome project for quite a long time.

A few days ago I noticed that my "visitors" badge is not working. After taking a closer look I discovered that all the API endpoints (https://hits.dwyl.com/D00Movenok/D00Movenok, https://hits.dwyl.com/D00Movenok/D00Movenok.json, https://hits.dwyl.com/D00Movenok/D00Movenok.svg) return an Internal Server Error (500).

Seems that something was broken on the backend.

**Comment by FurryR** [comment]
I have the same issue.
It affected to my projects; is there anything I can do to help?

**Comment by bearsyankees** [comment]
Same!

**Comment by nelsonic** [comment]
Sadly, the PostgreSQL on Fly.io is not reliable. Zero warning when running out of disk space. Requires some time to recover ... 🙃

**Comment by LuchoTurtle** [comment]
@nelsonic the only way to fix this is to increase disk space? Don't have access to the logs (for some reason)

**Comment by nelsonic** [comment]
The volume doesn't _appear_ to be full ... the only one that is used is `4,045 MB` of `10GB` ...
https://fly.io/apps/hits-db/volumes 
<img width="1430" alt="image" src="https://github.com/dwyl/hits/assets/194400/736f56d8-0014-4615-806f-aab0d34c5305">

<img width="462" alt="image" src="https://github.com/dwyl/hits/assets/194400/1a7ab250-b1a6-4726-8936-bf80270cab5e">

@LuchoTurtle you are admin. Feel free to poke around non-destructively and see what can be done. 🙏

**Comment by LuchoTurtle** [comment]
The logs clearly state that the problem is with DB connection. It is currently suspended.

<img width="1264" alt="image" src="https://github.com/dwyl/hits/assets/17494745/580e077a-8cba-41dc-beb0-7e38b9d3109b">

Can I just start it? @nelsonic

**Comment by nelsonic** [comment]
If it's just a case of booting the DB instance, go for it and monitor closely. But I suspect it might need a boost in RAM. Which will tip us over into the next cost bracket... let's try and see what happens.

**Comment by LuchoTurtle** [comment]
Just started it. By looking at the logs, the DB seems to be working properly as well. 

https://hits.dwyl.com/dwyl/hits.svg?style=flat-square

The hits are looking good as well.
If it stops again, we should be able to receive an e-mail of memory issues. It's running on  only 564mb of RAM, after all

**Comment by LuchoTurtle** [comment]
It's been roughly an hour since deploying and it seems to be stable.

https://fly.io/apps/hits-db/activity

I'm closing this issue. If anything happens, it can be reopened.

**Comment by nelsonic** [comment]
Thanks @LuchoTurtle 🙏

**Comment by nelsonic** [comment]
The issue is that the hits app is seeing silly volume of requests and Fly.io is throttling it. 🤦‍♂️ 
We need a more robust way of hosting this pet project. 💭

**Comment by nelsonic** [comment]
Fixed. [![HitCount](https://hits.dwyl.com/dwyl/hits.svg)](https://github.com/dwyl/hits)
Closing. ✅
