### ISSUE TITLE
BUG: Internal Server Error

### ISSUE THREAD

**Issue by haydenthai** [dwyl/hits#294]
https://hits.dwyl.com/haydenthai/haydenthai

<img width="447" alt="Screenshot 2024-08-27 at 8 55 16 PM" src="https://github.com/user-attachments/assets/a3f0371a-922f-42cf-9d8b-b2ccba91ba2a">

My badge shows the default text unfortunately
<img width="121" alt="Screenshot 2024-08-27 at 8 55 38 PM" src="https://github.com/user-attachments/assets/d1a95960-eaab-4cd2-b959-734fbf8486d4">

The website looks to be working fine
https://hits.dwyl.com/

<img width="1440" alt="Screenshot 2024-08-27 at 8 56 09 PM" src="https://github.com/user-attachments/assets/476aa727-666f-4547-bdf1-6b1e288ce7a3">

**Comment by haydenthai** [comment]
Also thanks so much for the repo, the hits is awesome!!

**Comment by nelsonic** [comment]
Credit card expired ... 🤦‍♂️ 
https://fly.io/dashboard/hits/billing
<img width="1330" alt="image" src="https://github.com/user-attachments/assets/fb513f95-1c7a-4115-ab48-68fa5d85e5de">

When I attempt to login with the `admin` account to update the payment details I see the following "snack bar" error:

<img width="315" alt="image" src="https://github.com/user-attachments/assets/61965f69-72ff-4f64-a177-387e23e18f75">

Sent a Reset password request ... another "snack bar" ... 🙄 

<img width="400" alt="image" src="https://github.com/user-attachments/assets/0828d07f-5587-4f6f-8d4a-f87e3add84b6">

Email hasn't come through and it's been 15 mins ... ⏳

**Comment by nelsonic** [comment]
Continue: https://fly.io/apps/hits-db

**Comment by cristminix** [comment]
still no updates cz no one who donates to this projects ?? is it true ?? :lol

**Comment by nelsonic** [comment]
Having a great time access the Fly.io account ...
![image](https://github.com/user-attachments/assets/8fb58242-9584-45b6-b37a-1826079173cf)

**Comment by nelsonic** [comment]
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/06eb0356-0d4d-4408-8ed1-fb7c8a6a62d3">

Manually stopping.

Modal ("snack bar") informs me the machine is stopping: 
<img width="336" alt="image" src="https://github.com/user-attachments/assets/e0057c52-288a-4551-9fdd-318acfe0570d">

Now restarting: 
<img width="336" alt="image" src="https://github.com/user-attachments/assets/81c69828-0c6f-4301-ab72-83fec86a48fc">

Another "snackbar": 
<img width="339" alt="image" src="https://github.com/user-attachments/assets/2c0e2d5b-a7c6-42ba-aa30-af055990ed26">

Getting peckish ...

**Comment by nelsonic** [comment]
<img width="328" alt="image" src="https://github.com/user-attachments/assets/9d71b21e-2639-455b-abd2-46ecb61d7354">

Working: 
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/0143e44f-6978-4297-87a7-6e70a66e831c">

**Comment by nelsonic** [comment]
@haydenthai https://hits.dwyl.com/haydenthai/haydenthai.svg is ![hits-badge](https://hits.dwyl.com/haydenthai/haydenthai.svg)

**Comment by nelsonic** [comment]
Basically Fly.io migrated our production Postgres DB and didn't ensure everything was working ... 😫
