### ISSUE TITLE
Rename from Hits to something more "ATM"?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#39]
**A**ctionable **T**estable **M**etrics?
@iteles what was the middle word again...?

**Comment by iteles** [comment]
Transformative ;) But we also discussed Testable...!

**Comment by nelsonic** [comment]
@iteles what do we think of re-naming to `oatmeal` _o**ATM**eal_... 
as in "Find your ATM"... or we find ATMs for Breakfast...! 😉

**Comment by iteles** [comment]
Already renamed something else to that! https://github.com/dwyl/atm
