### ISSUE TITLE
502 Bad Gateway Two Days now

### ISSUE THREAD

**Issue by goxr3plus** [dwyl/hits#62]
Is the site down or something :(

**Comment by nelsonic** [comment]
@goxr3plus thank you for opening this issue.
Can you please inform where you are using a Hits badge?

**Comment by nelsonic** [comment]
@goxr3plus this should now be resolved. thanks again for reporting. 👍

**Comment by nelsonic** [comment]
https://github.com/goxr3plus/FX-BorderlessScene
![image](https://user-images.githubusercontent.com/194400/56299595-3d839680-612c-11e9-8384-99608897c30e.png)

**Comment by goxr3plus** [comment]
Thank you so much for fixing? Can i know what was actually happening and it
was not working? Just a curious question from a developer :)

**Comment by iteles** [comment]
@goxr3plus Linked issue above should give you all the detail: https://github.com/dwyl/learn-devops/issues/52

Had to upgrade the Linode instance because it ran out of disk space!

Out of curiosity, where are you using hits?

**Comment by goxr3plus** [comment]
In all my top github repositories, like XR3PALAYER, JFXBrowser etc :) I am
very happy with it.


Thank you so much for making it 💓 💓 💓 💓
