### ISSUE TITLE
Hit count is reporting 502 Bad Gateway 

### ISSUE THREAD

**Issue by goxr3plus** [dwyl/hits#64]
http://hits.dwyl.io/goxr3plus/java-stream-player

**Comment by nelsonic** [comment]
https://github.com/goxr3plus/java-stream-player
![image](https://user-images.githubusercontent.com/194400/56975965-c9a0af80-6b69-11e9-8e58-1ccfb5a4a22b.png)

**Comment by goxr3plus** [comment]
💓
