### ISSUE TITLE
Perf: add index to hits.repo_id to speed up aggregate queries

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#72]
At present the aggregate `SELECT COUNT(repo_id)` query #71 is _relatively_ slow because it's not optimised. This is not a major bottleneck in the App _yet_ because we don't have a lot of data in the DB so `COUNT(*)` queries are 1ms ... but as soon as we do have a few billion rows, we can expect it to degrade  ... 
When that happens we should add an index and the docs to show others how to do it.

**Comment by SimonLab** [comment]
I think repo_id is does now have an index:
![image](https://user-images.githubusercontent.com/6057298/154247039-564887b4-d57a-45e7-87a3-54287ec25baa.png)

**Comment by nelsonic** [comment]
@SimonLab looks good. 👍
