### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by IndrajeetPatil** [dwyl/hits#87]
At http://hits.dwyl.io/, I am getting- 

![image](https://user-images.githubusercontent.com/11330453/73882949-54ce7480-4863-11ea-811b-9f2b1a26c56e.png)

**Comment by samisalreadytaken** [comment]
The domain was moved from `.io` to `.com`.

**Comment by IndrajeetPatil** [comment]
I guess http://hits.dwyl.com/ is down temporarily?

![image](https://user-images.githubusercontent.com/11330453/74223604-6080c780-4cb7-11ea-8210-45b7a04467fe.png)

**Comment by MexsonFernandes** [comment]
The site is still down.
![image](https://user-images.githubusercontent.com/22270770/117232802-902d6980-ae3f-11eb-92ff-942d30f3e159.png)
