### ISSUE TITLE
http://hits.dwyl.io/ does NOT work!

### ISSUE THREAD

**Issue by kerolloz** [dwyl/hits#89]

**Comment by iteles** [comment]
This has already been raised in #87 and there is a PR that was open for it less than 24 hours ago which is awaiting review https://github.com/dwyl/hits/pull/88.

**Comment by nelsonic** [comment]
@kerolloz please don't use this service it's NOT _for_ you!

**Comment by kerolloz** [comment]
@iteles Thank you

Hey @nelsonic. Thank you too, such a rude comment. You don't get to say what is for me and what is not. Mind your own business. Stop meddling in what doesn't concern you. have a good day :smiley:.

**Comment by kerolloz** [comment]
@nelsonic Why don't you read your code of conduct :smiley:?
https://github.com/dwyl/hits/blob/master/CODE_OF_CONDUCT.md
![image](https://user-images.githubusercontent.com/36763164/73962799-c49e3700-4917-11ea-8e0f-e939c59934e5.png)
