### ISSUE TITLE
502 gateway for Hit Counter

### ISSUE THREAD

**Issue by sakshatshinde** [dwyl/hits#93]
[Hit Counter](https://hits.dwyl.com/) Seems to be down, and as a result the hit-counter badge is broken

Err: **502** Bad Gateway

**Comment by hchiam** [comment]
Same for me too.

**Comment by silentsoft** [comment]
Same for me too.

**Comment by shauryauppal** [comment]
Same for me

**Comment by nm17** [comment]
Any news on ETA?

**Comment by sakshatshinde** [comment]
This seems to have been resolved. Closing the issue.
