### ISSUE TITLE
it seems to be 502

### ISSUE THREAD

**Issue by bohanjun** [dwyl/hits#94]
Error 502 Ray ID: 5783e3478c25a928 • 2020-03-23 00:03:10 UTC
Bad gateway
You
Browser
Working
Singapore
Cloudflare
Working
hits.dwyl.com
Host
Error
What happened?
The web server reported a bad gateway error.

What can I do?
Please try again in a few minutes.

Cloudflare Ray ID: 5783e3478c25a928 • Your IP: 183.192.42.160 • Performance & security by Cloudflare

**Comment by nelsonic** [comment]
Thanks for reporting this. We are investigating. 🔍

**Comment by lukeeey** [comment]
its been like this for weeks, if not months now
https://hits.dwyl.com/

![image](https://user-images.githubusercontent.com/32024335/77706066-3a8a5a80-6fb9-11ea-95ff-5ccd396242b2.png)

**Comment by aravindnc** [comment]
Still same. Getting 502.

**Comment by pingsutw** [comment]
same issue, what happens to the server?

**Comment by manilarome** [comment]
It's working again for me now!

**Comment by aravindnc** [comment]
Working fine now.

**Comment by pingsutw** [comment]
it's working now, thanks to everyone.

**Comment by bohanjun** [comment]
thanks

**Comment by iteles** [comment]
Closing this, as per comments above. Thanks everyone 🙌
