### ISSUE TITLE
Update Phoenix and other dependencies

### ISSUE THREAD

**Issue by SimonLab** [dwyl/hits#97]
- [x] Update Phoenix to 1.5 https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f
- [x] Update other dependencies to avoid warning message:
![image](https://user-images.githubusercontent.com/6057298/83013547-1b3d9700-a015-11ea-95c5-635a1c864426.png)

**Comment by nelsonic** [comment]
Recently updated to Phoenix `1.6.2` in #128 ✅ 
(_thanks for opening this issue @SimonLab_ ⭐)
